DevPortfolio/Models/Entety/AboutMe.cs
using System.Security.AccessControl;

namespace DevPortfolio.Models.Entety
{
    public class AboutMe
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Name { get; set; }
       
        

        public AboutMe(int id, string title, string name)
        {
            Id = id;
            Title = title;
            Name = name;
        }
    }
}

DevPortfolio/Models/Entety/Contact.cs
using System.ComponentModel.DataAnnotations;

namespace DevPortfolio.Models.Entety
{
    public class Contact
    {

        [Key]
        public int Id { get; set; }
        [Display(Name = "نام")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        [MinLength(3,ErrorMessage = "{0} نمیتوتند از {1} کاراکتر کمتر باشد")]
        [MaxLength(25,ErrorMessage = "{0} نمی تواند از {1} کاراکتر بیشتر باشد")]
        public string Name { get; set; }
        [Display(Name = "ایمیل")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        [EmailAddress]
        [MinLength(8, ErrorMessage = "{0} نمیتوتند از {1} کاراکتر کمتر باشد")]
        [MaxLength(250, ErrorMessage = "{0} نمی تواند از {1} کاراکتر بیشتر باشد")]
        public string Email { get; set; }
        [Display(Name = "موضوع")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        public string Subject { get; set; }
        [Display(Name = "موضوع")]
        public string Description { get; set; }
    }
}

DevPortfolio/Models/ErrorViewModel.cs
using System;

namespace DevPortfolio.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DevPortfolio/Controllers/HomeController.cs
using DevPortfolio.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using DevPortfolio.Models.Entety;

namespace DevPortfolio.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }


        [HttpGet]
        public IActionResult Contact()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Contact(Contact contact)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Error = "اطلاعات وارد شده اشتباه هستند";
                return View(contact);
            }

            ViewBag.success = "پیغام شما با موفقیت ارسال شد. باتشکر";
            return View();
        }












        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DevPortfolio/ViewComponents/SiteViewComponent.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using DevPortfolio.Models.Entety;
using Microsoft.AspNetCore.Mvc;

namespace DevPortfolio.ViewComponents
{
    public class AboutSiteViewComponent : Microsoft.AspNetCore.Mvc.ViewComponent
    {
        public  IViewComponentResult Invoke()
        {
            var about = new List<AboutMe>
            {
                new AboutMe(1,"تاریخ تولد","1377"),
                new AboutMe(2,"وبسایت","-"),
                new AboutMe(3,"تلفن","09168467533"),
                new AboutMe(4,"شهر","خرم اباد"),
                new AboutMe(8,"سن","25"),
                new AboutMe(6,"درجه","Sinior"),
                new AboutMe(7,"ایمیل","Alirasty1997@gmail.com")
             
            };
            return View("AboutSite",about);
        }
    }

    //public class AboutSiteViewComponent : Microsoft.AspNetCore.Mvc.ViewComponent
    //{
    //    public async Task<IViewComponentResult> InvokeAsync()
    //    {
    //        var about = new List<AboutMe>
    //        {
    //            new AboutMe(1,"تاریخ تولد","1377"),
    //            new AboutMe(2,"وبسایت","-"),
    //            new AboutMe(3,"تلفن","09168467533"),
    //            new AboutMe(4,"شهر","خرم اباد"),
    //            new AboutMe(8,"سن","25"),
    //            new AboutMe(6,"درجه","Sinior"),
    //            new AboutMe(7,"ایمیل","Alirasty1997@gmail.com")

    //        };
    //        return View("AboutSite", about);
    //    }
    //}


}

DevPortfolio/Views/Home/Contact.cshtml
  @model DevPortfolio.Models.Entety.Contact


<section id="contact" class="contact">
      <div class="container">

          <div class="section-title">
              <h2>درباره ما</h2>
          </div>

          <div class="row" data-aos="fade-in">

              <div class="col-lg-7 mt-5 mt-lg-0 d-flex align-items-stretch">
                  @if (!string.IsNullOrWhiteSpace(ViewBag.success))
                  {
                      <div class="alert-success p-5">
                          <p>
                            @ViewBag.success
                          </p>
                      </div>
                  }
                  @if (!string.IsNullOrWhiteSpace(ViewBag.Error))
                  {
                      <div class="alert-danger p-5">
                          <p>
                            @ViewBag.Error
                          </p>
                      </div>
                  }
                  <form method="post" role="form" asp-action="Contact"asp-controller="Home" class="php-email-form">
                      <div class="row">
                          <div class="form-group col-md-6">
                              <label for="name">نام</label>
                              <input type="text" asp-for="Name" class="form-control" id="name" required>
                               <span asp-validation-for="Name"></span>
                              </div>
                          <div class="form-group col-md-6">
                              <label for="name">ایمیل</label>
                            
                              <input type="email" class="form-control" asp-for="Email" id="email" required>
                              <span asp-validation-for="Email"></span>
                          </div>
                      </div>
                      <div class="form-group">
                          <label for="name">موضوع</label>
                          <input type="text" class="form-control" asp-for="Subject" id="subject" required>
                      </div>
                      <div class="form-group">
                          <label for="name">پیغام</label>
                          <textarea class="form-control" asp-for="Description" rows="10" required></textarea>
                      </div>
                      <div class="my-3">
                          <div class="loading">Loading</div>
                          <div class="error-message"></div>
                          <div class="sent-message">Your message has been sent. Thank you!</div>
                      </div>
                      <div class="text-center"><button type="submit">ارسال</button></div>
                  </form>
              </div>

              <div class="col-lg-5 d-flex align-items-stretch">
                  <div class="info">
                      <div class="address">
                          <i class="bi bi-geo-alt"></i>
                          <h4>Location:</h4>
                          <p>A108 Adam Street, New York, NY 535022</p>
                      </div>

                      <div class="email">
                          <i class="bi bi-envelope"></i>
                          <h4>Email:</h4>
                          <p>info@example.com</p>
                      </div>

                      <div class="phone">
                          <i class="bi bi-phone"></i>
                          <h4>Call:</h4>
                          <p>+1 5589 55488 55s</p>
                      </div>

                      <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12097.433213460943!2d-74.0062269!3d40.7101282!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xb89d1fe6bc499443!2sDowntown+Conference+Center!5e0!3m2!1smk!2sbg!4v1539943755621" frameborder="0" style="border: 0; width: 100%; height: 290px;" allowfullscreen></iframe>
                  </div>
              </div>
          </div>
      </div>
  </section>

DevPortfolio/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

  <section id="hero" class="d-flex flex-column justify-content-center align-items-center">
    <div class="hero-container" data-aos="fade-in">
      <h1>Ali Rasty</h1>
      <p>I'm <span class="typed" data-typed-items="Designer, Developer, Freelancer, Photographer"></span></p>
    </div>
  </section><!-- End Hero -->

  <main id="main">


    @await Component.InvokeAsync("AboutSite")



    <!-- ======= Skills Section ======= -->
    <section id="skills" class="skills section-bg">
      <div class="container">

        <div class="section-title">
          <h2>مهارت ها</h2>
            <p>
                Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit sint consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea. Quia fugiat sit in iste officiis commodi quidem hic quas.
            </p>
        </div>

        <div class="row skills-content" style="direction: ltr">

          <div class="col-lg-6" data-aos="fade-up">

            <div class="progress" style="text-align: left;">
              <span class="skill">HTML <i class="val"></i></span>
              <div class="progress-bar-wrap">
                  <div class="progress-bar" role="progressbar" style="width: 25%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">25%</div>   
               </div>
            </div>

            <div class="progress" style="text-align: left;">
              <span class="skill">CSS <i class="val"></i></span>
                <div class="progress-bar-wrap">
                    <div class="progress-bar" role="progressbar" style="width: 85%;" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100">85%</div>   
                </div>
            </div>

            <div class="progress" style="text-align: left;">
              <span class="skill">JavaScript <i class="val"></i></span>
                <div class="progress-bar-wrap">
                    <div class="progress-bar" role="progressbar" style="width: 55%;" aria-valuenow="55" aria-valuemin="0" aria-valuemax="100">55%</div>   
                </div>
            </div>

          </div>

          <div class="col-lg-6" data-aos="fade-up" data-aos-delay="100">

            <div class="progress" style="text-align: left;">
              <span class="skill">PHP <i class="val"></i></span>
                <div class="progress-bar-wrap">
                    <div class="progress-bar" role="progressbar" style="width: 45%;" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100">45%</div>   
                </div>
            </div>

            <div class="progress" style="text-align: left;">
              <span class="skill">WordPress/CMS <i class="val"></i></span>
                <div class="progress-bar-wrap">
                    <div class="progress-bar" role="progressbar" style="width: 85%;" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100">85%</div>   
                </div>
            </div>

            <div class="progress" style="text-align: left;">
              <span class="skill">Photoshop <i class="val"></i></span>
                <div class="progress-bar-wrap">
                    <div class="progress-bar" role="progressbar" style="width: 35%;" aria-valuenow="35" aria-valuemin="0" aria-valuemax="100">35%</div>   
                </div>
            </div>

          </div>

        </div>

      </div>
    </section><!-- End Skills Section -->

   
    <section id="resume" class="resume">
      <div class="container">

        <div class="section-title">
          <h2>رزومه</h2>
          <p>Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit sint consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea. Quia fugiat sit in iste officiis commodi quidem hic quas.</p>
        </div>

        <div class="row">
          <div class="col-lg-6" data-aos="fade-up">
            <h3 class="resume-title">Sumary</h3>
            <div class="resume-item pb-0">
              <h4>Alex Smith</h4>
              <p><em>Innovative and deadline-driven Graphic Designer with 3+ years of experience designing and developing user-centered digital/print marketing material from initial concept to final, polished deliverable.</em></p>
              <ul>
                <li>Portland par 127,Orlando, FL</li>
                <li>(123) 456-7891</li>
                <li>alice.barkley@example.com</li>
              </ul>
            </div>

            <h3 class="resume-title">Education</h3>
            <div class="resume-item">
              <h4>Master of Fine Arts &amp; Graphic Design</h4>
              <h5>2015 - 2016</h5>
              <p><em>Rochester Institute of Technology, Rochester, NY</em></p>
              <p>Qui deserunt veniam. Et sed aliquam labore tempore sed quisquam iusto autem sit. Ea vero voluptatum qui ut dignissimos deleniti nerada porti sand markend</p>
            </div>
            <div class="resume-item">
              <h4>Bachelor of Fine Arts &amp; Graphic Design</h4>
              <h5>2010 - 2014</h5>
              <p><em>Rochester Institute of Technology, Rochester, NY</em></p>
              <p>Quia nobis sequi est occaecati aut. Repudiandae et iusto quae reiciendis et quis Eius vel ratione eius unde vitae rerum voluptates asperiores voluptatem Earum molestiae consequatur neque etlon sader mart dila</p>
            </div>
          </div>
          <div class="col-lg-6" data-aos="fade-up" data-aos-delay="100">
            <h3 class="resume-title">Professional Experience</h3>
            <div class="resume-item">
              <h4>Senior graphic design specialist</h4>
              <h5>2019 - Present</h5>
              <p><em>Experion, New York, NY </em></p>
              <ul>
                <li>Lead in the design, development, and implementation of the graphic, layout, and production communication materials</li>
                <li>Delegate tasks to the 7 members of the design team and provide counsel on all aspects of the project. </li>
                <li>Supervise the assessment of all graphic materials in order to ensure quality and accuracy of the design</li>
                <li>Oversee the efficient use of production project budgets ranging from $2,000 - $25,000</li>
              </ul>
            </div>
            <div class="resume-item">
              <h4>Graphic design specialist</h4>
              <h5>2017 - 2018</h5>
              <p><em>Stepping Stone Advertising, New York, NY</em></p>
              <ul>
                <li>Developed numerous marketing programs (logos, brochures,infographics, presentations, and advertisements).</li>
                <li>Managed up to 5 projects or tasks at a given time while under pressure</li>
                <li>Recommended and consulted with clients on the most appropriate graphic design</li>
                <li>Created 4+ design presentations and proposals a month for clients and account managers</li>
              </ul>
            </div>
          </div>
        </div>

      </div>
    </section>


    
    <section id="services" class="services">
      <div class="container">

        <div class="section-title">
          <h2>سرویس ها</h2>
          <p>Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit sint consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea. Quia fugiat sit in iste officiis commodi quidem hic quas.</p>
        </div>

        <div class="row">
          <div class="col-lg-4 col-md-6 icon-box" data-aos="fade-up">
            <div class="icon"><i class="bi bi-briefcase"></i></div>
            <h4 class="title"><a href="">Lorem Ipsum</a></h4>
            <p class="description">Voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident</p>
          </div>
          <div class="col-lg-4 col-md-6 icon-box" data-aos="fade-up" data-aos-delay="100">
            <div class="icon"><i class="bi bi-card-checklist"></i></div>
            <h4 class="title"><a href="">Dolor Sitema</a></h4>
            <p class="description">Minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat tarad limino ata</p>
          </div>
          <div class="col-lg-4 col-md-6 icon-box" data-aos="fade-up" data-aos-delay="200">
            <div class="icon"><i class="bi bi-bar-chart"></i></div>
            <h4 class="title"><a href="">Sed ut perspiciatis</a></h4>
            <p class="description">Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur</p>
          </div>
          <div class="col-lg-4 col-md-6 icon-box" data-aos="fade-up" data-aos-delay="300">
            <div class="icon"><i class="bi bi-binoculars"></i></div>
            <h4 class="title"><a href="">Magni Dolores</a></h4>
            <p class="description">Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum</p>
          </div>
          <div class="col-lg-4 col-md-6 icon-box" data-aos="fade-up" data-aos-delay="400">
            <div class="icon"><i class="bi bi-brightness-high"></i></div>
            <h4 class="title"><a href="">Nemo Enim</a></h4>
            <p class="description">At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque</p>
          </div>
          <div class="col-lg-4 col-md-6 icon-box" data-aos="fade-up" data-aos-delay="500">
            <div class="icon"><i class="bi bi-calendar4-week"></i></div>
            <h4 class="title"><a href="">Eiusmod Tempor</a></h4>
            <p class="description">Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi</p>
          </div>
        </div>

      </div>
    </section>

  <partial name="Contact"/>

  </main>

DevPortfolio/Views/Shared/Components/AboutSite/AboutSite.cshtml
@model IEnumerable<DevPortfolio.Models.Entety.AboutMe>

 <section id="about" class="about">
      <div class="container">

        <div class="section-title">
          <h2>درباره من</h2>
            <p>
                در این رزومه قصد دارم درمورد خودم توضیحاتی بدهم.
            </p>
        </div>

        <div class="row">
          <div class="col-lg-4" data-aos="fade-right">
            <img src="~/assets/pic/me.jpg" class="img-fluid" alt="">
          </div>
          <div class="col-lg-8 pt-4 pt-lg-0 content" data-aos="fade-left">
            <h3>برنامه نویس و طراح هستم (ui/ux)</h3>
            <p class="fst-italic">
             توضیحات
            </p>
            <div class="row">
                @foreach (var item in Model)
                {
                    if (item.Id <= 4)
                    {
                        <div class="col-lg-6">
                            <ul>
                                <li>
                                    <i class="bi bi-chevron-left"></i> 
                                    <strong>@item.Title:</strong> 
                                    <span>@item.Name</span>
                                </li>
                            </ul>
                        </div> 
                    }
                }
                @foreach (var item in Model)
                {
                    if (item.Id > 4)
                    {
                        <div class="col-lg-6">
                            <ul>
                                <li>
                                    <i class="bi bi-chevron-left"></i> 
                                    <strong>@item.Title:</strong> 
                                    <span>@item.Name</span>
                                </li>
                            </ul>
                        </div> 
                    }
                }
               


               
            </div>
            <p>.NET پلتفرمی برای توسعه است که متن باز(open source)، چندسکویی (cross platform) و رایگان است. این پلتفرم توسط شرکت مایکروسافت برای ساختن انواع مختلفی از برنامه ها ایجاد شده است. با .NET شما می توانید از چندین زبان، ویرایشگر و کتابخانه برای ساختن برنامه های وب، موبایل، اپلیکیشن، بازی و IOT استفاده کنید. </p>
          </div>
        </div>

      </div>
    </section>

DevPortfolio/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="fa">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>iPortfolio AliRasty - @ViewData["Title"]</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="~/assets/vendor/aos/aos.css" rel="stylesheet">
  <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="~/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
  <link href="~/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">
  <!-- CSS -->
  <link rel="stylesheet" href="https://cdn.rtlcss.com/bootstrap/v4.5.3/css/bootstrap.min.css" integrity="sha384-JvExCACAZcHNJEc7156QaHXTnQL3hQBixvj5RV5buE7vgnNEzzskDtx9NQ4p6BJe" crossorigin="anonymous">

  <!-- Template Main CSS File -->
  <link href="~/assets/css/style.css" rel="stylesheet">


</head>

<body dir="rtl">

  <!-- ======= Mobile nav toggle button ======= -->
  <i class="bi bi-list mobile-nav-toggle d-xl-none"></i>

  <!-- ======= Header ======= -->
  <header id="header">
    <div class="d-flex flex-column">

      <div class="profile">
        <img src="~/assets/pic/me2.jpg" alt="" class="img-fluid rounded-circle">
        <h1 class="text-light"><a href="index.html">علی راستی</a></h1>
        <div class="social-links mt-3 text-center">
          <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
          <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
          <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
          <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
          <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
        </div>
      </div>

      <nav id="navbar" class="nav-menu navbar">
        <ul>
          <li><a href="#hero" class="nav-link scrollto active"><i class="bx bx-home"></i> <span>Home</span></a></li>
          <li><a href="#about" class="nav-link scrollto"><i class="bx bx-user"></i> <span>About</span></a></li>
          <li><a href="#resume" class="nav-link scrollto"><i class="bx bx-file-blank"></i> <span>Resume</span></a></li>
          <li><a href="#portfolio" class="nav-link scrollto"><i class="bx bx-book-content"></i> <span>Portfolio</span></a></li>
          <li><a href="#services" class="nav-link scrollto"><i class="bx bx-server"></i> <span>Services</span></a></li>
          <li><a href="#contact" class="nav-link scrollto"><i class="bx bx-envelope"></i> <span>Contact</span></a></li>
        </ul>
      </nav><!-- .nav-menu -->
    </div>
  </header><!-- End Header -->

    @RenderBody()

  <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="container">
      <div class="copyright">
        <strong><span>Portfolio AliRasty</span></strong>
      </div>
      
    </div>
  </footer><!-- End  Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

<!-- Vendor JS Files -->
<!-- jQuery and JS bundle w/ Popper.js -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.rtlcss.com/bootstrap/v4.5.3/js/bootstrap.bundle.min.js" integrity="sha384-40ix5a3dj6/qaC7tfz0Yr+p9fqWLzzAXiwxVLt9dw7UjQzGYw6rWRhFAnRapuQyK" crossorigin="anonymous"></script>
  <script src="~/assets/vendor/purecounter/purecounter_vanilla.js"></script>
  <script src="~/assets/vendor/aos/aos.js"></script>
  <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="~/assets/vendor/glightbox/js/glightbox.min.js"></script>
  <script src="~/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="~/assets/vendor/swiper/swiper-bundle.min.js"></script>
  <script src="~/assets/vendor/typed.js/typed.min.js"></script>
  <script src="~/assets/vendor/waypoints/noframework.waypoints.js"></script>
  <script src="~/assets/vendor/php-email-form/validate.js"></script>

  <!-- Template Main JS File -->
<script src="~/assets/js/main.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>

<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>